package me.magnum.melonds.impl.emulator

import android.os.Handler
import android.os.HandlerThread
import android.os.Looper
import android.os.MessageQueue
import android.os.ParcelFileDescriptor
import java.io.FileInputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.min

class EmulatorMessageQueue(private val eventHandler: EventHandler) {

    fun interface EventHandler {
        /**
         * @param type The type of event generated by the emulator
         * @param data The buffer containing optional data associated with the event. The buffer is only valid for the duration of the call
         */
        fun onEmulatorEvent(type: EmulatorEventType, data: ByteBuffer)
    }

    companion object {
        internal const val MAX_DATA_SIZE_BYTES = 128
        private const val READ_BUFFER_SIZE_BYTES = 512

        /**
         * Initialize the native message pipe and returns the file descriptor through which the messages will be sent.
         * @return File descriptor for reading events, or -1 on error
         */
        @JvmStatic
        private external fun initMessagePipe(): Int

        /**
         * Close the native message pipe.
         */
        @JvmStatic
        private external fun closeMessagePipe()
    }

    private val handlerThread = HandlerThread("EmulatorMessageQueue").apply { start() }
    private val handler = Handler(handlerThread.looper)

    private var messagesFileDescriptor: ParcelFileDescriptor? = null
    private var inputStream: FileInputStream? = null
    private var isRunning = false
    private val readBuffer = ByteBuffer.allocateDirect(READ_BUFFER_SIZE_BYTES)
    private val frameDecoder = EmulatorEventFrameDecoder()

    fun start() {
        handler.post {
            if (isRunning) {
                return@post
            }

            val looper = Looper.myLooper() ?: throw IllegalStateException("Current thread does not have a Looper")

            val readPipeFd = initMessagePipe()
            if (readPipeFd < 0) {
                throw RuntimeException("Failed to initialize native pipe")
            }

            val fileDescriptor = ParcelFileDescriptor.fromFd(readPipeFd)
            if (fileDescriptor == null) {
                throw RuntimeException("Failed to create ParcelFileDescriptor")
            }

            messagesFileDescriptor = fileDescriptor
            isRunning = true
            inputStream = FileInputStream(fileDescriptor.fileDescriptor)

            val watchedEvents = MessageQueue.OnFileDescriptorEventListener.EVENT_INPUT or
                MessageQueue.OnFileDescriptorEventListener.EVENT_ERROR
            looper.queue.addOnFileDescriptorEventListener(fileDescriptor.fileDescriptor, watchedEvents) { _, events ->
                if (!isRunning || events and MessageQueue.OnFileDescriptorEventListener.EVENT_ERROR != 0) {
                    stopOnHandlerThread()
                    return@addOnFileDescriptorEventListener 0
                }

                try {
                    if (!readEvents()) {
                        stopOnHandlerThread()
                        return@addOnFileDescriptorEventListener 0
                    }
                } catch (exception: Exception) {
                    exception.printStackTrace()
                    stopOnHandlerThread()
                    return@addOnFileDescriptorEventListener 0
                }

                watchedEvents
            }
        }
    }

    fun stop() {
        handler.post {
            if (!isRunning) {
                return@post
            }

            stopOnHandlerThread()
        }
    }

    fun cleanup() {
        stop()
        handlerThread.quitSafely()
    }

    private fun stopOnHandlerThread() {
        if (!isRunning) {
            return
        }

        isRunning = false
        messagesFileDescriptor?.let { fd ->
            Looper.myLooper()?.queue?.removeOnFileDescriptorEventListener(fd.fileDescriptor)
            fd.close()
        }

        inputStream = null
        messagesFileDescriptor = null
        frameDecoder.reset()
        closeMessagePipe()
    }

    private fun readEvents(): Boolean {
        val currentInputStream = inputStream ?: return false

        while (true) {
            readBuffer.clear()
            when (currentInputStream.channel.read(readBuffer)) {
                -1 -> return false
                0 -> return true
                else -> {
                    readBuffer.flip()
                    frameDecoder.consume(readBuffer, eventHandler::onEmulatorEvent)
                }
            }
        }
    }
}

internal class EmulatorEventFrameDecoder(
    private val maxPayloadSize: Int = EmulatorMessageQueue.MAX_DATA_SIZE_BYTES,
) {
    private val headerBuffer = ByteBuffer.allocate(Int.SIZE_BYTES * 2).order(ByteOrder.nativeOrder())
    private val payloadBuffer = ByteBuffer.allocate(maxPayloadSize).order(ByteOrder.nativeOrder())
    private var pendingType: EmulatorEventType? = null
    private var pendingPayloadLength: Int? = null

    fun consume(source: ByteBuffer, eventHandler: (EmulatorEventType, ByteBuffer) -> Unit) {
        while (source.hasRemaining()) {
            if (pendingPayloadLength == null) {
                transfer(source, headerBuffer)
                if (headerBuffer.hasRemaining()) {
                    return
                }

                headerBuffer.flip()
                val rawType = headerBuffer.int
                val payloadLength = headerBuffer.int
                headerBuffer.clear()

                if (payloadLength < 0 || payloadLength > maxPayloadSize) {
                    reset()
                    throw IllegalArgumentException("Invalid emulator event payload length: $payloadLength")
                }

                pendingType = EmulatorEventType.entries.firstOrNull { it.event == rawType }
                pendingPayloadLength = payloadLength
                payloadBuffer.clear()
                payloadBuffer.limit(payloadLength)

                if (payloadLength == 0) {
                    dispatch(eventHandler)
                }
            } else {
                transfer(source, payloadBuffer)
                if (!payloadBuffer.hasRemaining()) {
                    dispatch(eventHandler)
                }
            }
        }
    }

    fun reset() {
        headerBuffer.clear()
        payloadBuffer.clear()
        pendingType = null
        pendingPayloadLength = null
    }

    private fun dispatch(eventHandler: (EmulatorEventType, ByteBuffer) -> Unit) {
        payloadBuffer.flip()
        pendingType?.let { type ->
            eventHandler(type, payloadBuffer.asReadOnlyBuffer().order(ByteOrder.nativeOrder()))
        }
        payloadBuffer.clear()
        pendingType = null
        pendingPayloadLength = null
    }

    private fun transfer(source: ByteBuffer, destination: ByteBuffer) {
        val byteCount = min(source.remaining(), destination.remaining())
        val oldLimit = source.limit()
        source.limit(source.position() + byteCount)
        destination.put(source)
        source.limit(oldLimit)
    }
}