name: Tests

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: zulu
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Run unit tests
        run: |
          chmod +x ./gradlew
          ./gradlew :app:testGitHubProdDebugUnitTest
